var List = [
"Would you rather live in a world where everything you dream at night becomes reality the next day or in a world where every time you fall asleep, you die in your sleep but wake up the next day with no memory of having died?",
"Would you rather have the ability to see ten minutes into the future or the ability to relive any moment in your life again?",
"Would you rather have feet made of springs or hands that glow in the dark?",
"Would you rather have a never-ending headache or constantly taste soap in your mouth?",
"Would you rather have arms that are 10 times longer than your body, or legs that are 10 times shorter?",
"Would you rather have fingers made of jellybeans or a tongue made of cotton candy?",
"Would you rather have a pet dolphin that can control the waves or a pet tiger that can shoot lasers from its eyes?",
"Would you rather have the power to turn objects into gold but it only lasts for 5 minutes, or have the power to turn objects into diamonds but it only lasts for 10 seconds?",
"Would you rather have skin that sparkles in the dark or hair that reacts to music with different colors?",
"Would you rather constantly hear the sound of someone chewing with their mouth open or constantly experience the feeling of wearing wet socks?",
"Would you rather have the power to heal any illness or injury but only once a year or have the power to give yourself and anyone you choose immortality but at the cost of losing all your memories?",
"Would you rather live in a world without music or a world without movies?",
"Would you rather have the power to bring someone back to life but someone else has to die in their place or have the power to erase someone from existence but you lose a year of your own life every time you use it?",
"Would you rather find two random strangers living in your attic or 100 large spiders living in your attic?",
"Would you rather be stranded on a deserted island alone, or stranded with your worst enemy?",
"Would you rather be stuck in a 24 hour time loop like groundhog day or a parallel universe where randomness is rigged to where you get the worst possible outcome for every event you're involved in?",
"Would you rather have every song you hear slowly turn into 'Baby Shark' or have every movie you watch be replaced with the same Adam Sandler film?",
"Would you rather always have a pebble in your shoe or have an itch you can never reach?",
"Would you rather have a constant buzzing sound in your ear or always feel like there's a hair tickling your face?",
"Would you rather have a wardrobe consisting only of itchy wool clothes or wear clothes that are two sizes too small?",
"Would you rather have to eat a plate of bugs every day or drink a glass of spoiled milk every day?",
"Would you rather always have a stuffy nose or have a perpetually dry mouth?",
"Would you rather have to speak at twice the volume of a normal conversation or whisper so softly that people struggle to hear you?",
"Would you rather always have bad breath, no matter how much you brush your teeth, or have a constant taste of something unpleasant in your mouth?",
"Would you rather have to walk on your knees for the rest of your life or hop on one foot?",
"Would you rather have a non-stop itch on the bottom of your foot or have an unrelenting tickle in your throat?",
"Would you rather have every song you hear slowly turn into 'Baby Shark' or have every movie you watch be replaced with the same Adam Sandler film?",
"Would you rather always have a pebble in your shoe or have an itch you can never reach?",
"Would you rather have a constant buzzing sound in your ear or always feel like there's a hair tickling your face?",
"Would you rather have a wardrobe consisting only of itchy wool clothes or wear clothes that are two sizes too small?",
"Would you rather have to eat a plate of bugs every day or drink a glass of spoiled milk every day?",
"Would you rather always have a stuffy nose or have a perpetually dry mouth?",
"Would you rather have to speak at twice the volume of a normal conversation or whisper so softly that people struggle to hear you?",
"Would you rather always have bad breath, no matter how much you brush your teeth, or have a constant taste of something unpleasant in your mouth?",
"Would you rather have to walk on your knees for the rest of your life or hop on one foot?",
"Would you rather have a non-stop itch on the bottom of your foot or have an unrelenting tickle in your throat?",
"Would you rather attend a never-ending lecture on a topic you find incredibly boring or be trapped in a room full of people arguing loudly?",
"Would you rather participate in a marathon barefoot on scorching hot pavement or compete in a swimming race filled with freezing cold water?",
"Would you rather be stuck in an elevator with a person who talks non-stop or be stranded on a desert island with someone who never speaks at all?",
"Would you rather attend a party where everyone is dressed in embarrassing costumes or go to a formal event where you are the only one in casual attire?",
"Would you rather attend a concert where the performer is completely out of tune or watch a movie where the plot makes absolutely no sense?",
"Would you rather be a contestant on a reality TV show where your most embarrassing moments are broadcasted or have your entire internet search history made public?",
"Would you rather have to give a public speech to a crowd of thousands with no preparation or perform a dance routine in front of professional dancers without any prior training?",
"Would you rather attend a dinner party where the food is extremely spicy to the point of discomfort or eat a meal where every dish tastes extremely bland?",
"Would you rather go to a theme park and only be allowed on the slowest and least exciting rides or visit a haunted house with the scariest and most intense scares?",
"Would you rather attend a sports event where your favorite team loses in a humiliating fashion or watch a live performance where all the actors forget their lines and stumble through the entire show?",
"Would you rather experience a year-long global economic recession that impacts job opportunities and financial stability or endure a decade of frequent natural disasters that disrupt infrastructure and cause widespread destruction?",
"Would you rather live in a world where everyone speaks a language you can't understand, making communication extremely challenging, or live in a world where nobody can see color, resulting in a dull and monochromatic existence?",
"Would you rather be part of a society where technology is permanently banned, requiring a return to a simpler way of life but limiting progress and convenience, or be part of a society where technology controls every aspect of life, resulting in constant surveillance and loss of privacy?",
"Would you rather live in a world where all forms of art, music, and literature are erased and forgotten, leading to a cultural void, or live in a world where all scientific and technological advancements are lost, hindering progress and innovation?",
"Would you rather witness the extinction of an endangered species of your choice, leading to irreversible ecological consequences, or witness the destruction of a world wonder such as the Great Barrier Reef or the Amazon rainforest, losing invaluable natural treasures?",
"Would you rather experience a perpetual drought that leads to severe water scarcity and agricultural challenges, resulting in widespread famine and displacement, or live in a world with rising sea levels, causing the loss of coastal cities and mass population migration?",
"Would you rather have a significant decrease in global biodiversity, resulting in imbalanced ecosystems and increased vulnerability to diseases, or have a worldwide pollution crisis, leading to polluted air, water, and soil with long-term health effects?",
"Would you rather live in a society where artistic expression is heavily censored and creativity is stifled, limiting freedom of expression, or live in a society where misinformation and fake news run rampant, eroding trust and distorting reality?",
"Would you rather be part of a world where all forms of physical touch and affection are prohibited, resulting in emotional detachment and loneliness, or live in a world where empathy and compassion no longer exist, leading to a lack of human connection and understanding?",
"Would you rather experience a global energy crisis, causing power outages and limited access to electricity, impacting various sectors and quality of life, or live in a world where food scarcity becomes a permanent issue, leading to hunger and malnutrition for many?"
]

export default List;